services:
  mossy-database:
    # Aurora PostgreSQL でサポートされるバージョンに合わせる
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "mossy-developer"
      POSTGRES_PASSWORD: "password"
    ports:
      # デフォの 5432 ポートは干渉すると面倒なので明示的に 15432 に変更している
      - "45432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mossy-developer"]
      interval: 5s
      timeout: 2s
      retries: 5
